/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package weatherapp;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static weatherapp.WeatherForm.daysOfTheWeek;

/**
 *
 * @author iyerg0445
 */
public class DetailedInfoPopup extends WeatherForm {
    //INITIAL VARIABLES
    String[] cols = new String[4];
    String[][] data = new String[8][4];
    DefaultTableModel model = new DefaultTableModel(data, cols);
    JTable table = new JTable(model);
    

    /**
     * Creates new form DetailedInfoPopup
     */
    public DetailedInfoPopup() {
        initComponents();
        JPanel panel = new JPanel(new BorderLayout());
       
        panel.add(table, BorderLayout.NORTH);
        //HEADERS
        model.setValueAt("DAY OF THE WEEK", 0,0);
        model.setValueAt("TEMPERATURE OUTSIDE",0,1);
        model.setValueAt("FEELS LIKE",0,2);
        model.setValueAt("CHANCE OF RAIN",0,3);
        
        //ACTUAL VALUES
        for(int i = 0; i < 7 ; i ++){
            model.setValueAt(daysOfTheWeek[i], i + 1, 0);
            model.setValueAt(weeklyForecast[i] + "°C", i + 1, 1);
            model.setValueAt(weeklyFeelsLike[i] + "°C", i + 1, 2);
            model.setValueAt(weeklyChanceOfRain[i],i + 1,3);
        }
        
        //SETTING UP THE NEW JFRAME
        JFrame frame = new JFrame();
        frame.add(panel);
        Dimension d = new Dimension(800,180);
        frame.setPreferredSize(d);
        frame.setLocationRelativeTo(null);
        frame.pack();
        frame.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailedInfoPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailedInfoPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailedInfoPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailedInfoPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailedInfoPopup();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
